### ISSUE TITLE
Add grandparents, personalize labels

### ISSUE THREAD

**Issue by NicholBr** [gschivley/climate-life-events#9]
Using all generations you would know makes sense: so start from grandparents. For older people, those could have been born before 1900.  Explicitly input the grandchild .. which many older people actually have (no prediction necessary).  

It may be nice if people can input the text label going with each year.  The app can give a default + prediction if it is left empty, but the user can input whoever they know fitting the rough generation.

**Comment by gschivley** [comment]
Thanks for the interest and suggestion. Any chance that you have some experience with html/css? Configuring layout is the hardest part of this for me.

**Comment by NicholBr** [comment]
Yes.. that I do have some experience with that. But it isn't clear to me why layout would be the big problem..  Where can I look? I've never actually done anything with git, github. So It may be an easy way to learn a bit of that.

**Comment by gschivley** [comment]
I haven't had time to play around with putting multiple option on a single line, shrinking the height of dropdown boxes, or styling a dropdown so that it looks reasonable in a line of text.

The code for this app is all in the app.py file. I'm using [Dash](https://plot.ly/dash/) to make the web app - it's written in Python, but the html elements should look familiar. You'll see a link for the css that I'm using, but it's also [possible to use a local file](https://community.plot.ly/t/serve-locally-option-with-additional-scripts-and-style-sheets/6974/6). 

If it's too much to try writing a version in Dash you can also mock something rough up with basic directions for what the html/css would look like.

**Comment by gschivley** [comment]
How's this for grandparents?

![image](https://user-images.githubusercontent.com/10373332/36678060-c2e343fc-1add-11e8-94dd-30b5ddc32cff.png)

**Comment by gschivley** [comment]
Now that grandparents have been added I'm going to close this. #8 is similar enough that customizing labels can be pulled under there.
